version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=transaction_system
      - DB_USERNAME=admin
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:80"  # Map port 80 from Nginx to 8000 on localhost

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: transaction_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8081:80"  # Changed from 8080 to 8081
    depends_on:
      - db
    networks:
      - app-network

  code-fix:
    image: transaction_system-app
    command: /bin/sh -c "vendor/bin/rector process && php vendor/bin/php-cs-fixer fix"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  code-check:
    image: transaction_system-app
    command: /bin/sh -c "vendor/bin/rector process --dry-run"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  style-check:
    image: transaction_system-app
    command: /bin/sh -c "php vendor/bin/php-cs-fixer fix --dry-run"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
